---
apiVersion: v2
icon: https://helm.sh/img/helm.svg
name: aks-node-termination-handler
version: 1.2.0
appVersion: "2.0.0"
description: Gracefully handle Azure Virtual Machines shutdown within Kubernetes
maintainers:
  - name: maksim-paskal  # Maksim Paskal
    email: paskal.maksim@gmail.com
  - name: vince-riv
    email: github@vince-riv.io
